### ISSUE TITLE
Issues with Method 2: Inplace Upgrade via Registry - The system was unable to find the specified registry key 

### ISSUE THREAD

**Issue by jed84** [builtbybel/Flyby11#11]
I am having issues with Method 2: Inplace Upgrade via Registry - The system was unable to find the specified registry key:

Log:
> 22:45:45 - Deactivated patch: (Method 2) Inplace Upgrade via Registry (Rufus method, not recommended by Microsoft)
> 22:45:45 - (Method 1) Automating Windows 11 Inplace Upgrade...
> 22:45:45 - Starting the download of the Windows 24H2 ISO...
> 22:45:45 - Output: Operacja ukoäczona pomylnie.
> 22:45:45 - Plugin executed command: reg delete "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\HwReqChk" /f
> 22:45:46 - Error: ERROR: The system was unable to find the specified registry key or value.
> 22:45:46 - Plugin executed command: reg delete "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\CompatMarkers" /f
> 22:45:46 - Error: ERROR: The system was unable to find the specified registry key or value.
> 22:45:46 - Plugin executed command: reg delete "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Shared" /f
> 22:45:46 - Error: ERROR: The system was unable to find the specified registry key or value.
> 22:45:46 - Plugin executed command: reg delete "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\TargetVersionUpgradeExperienceIndicators" /f
> 22:45:46 - Output: Operacja ukoäczona pomylnie.
> 22:45:46 - Plugin executed command: reg delete "HKLM\SYSTEM\Setup\MoSetup" /f /v AllowUpgradesWithUnsupportedTPMOrCPU
> 22:45:46 - Please Wait...

Flyby11 0.14 (Build 107) [La](https://github.com/builtbybel/Flyby11/releases/latest)

**Comment by Belim** [comment]
This is just a misunderstanding, the patch/ script also removes some keys from the registry under HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags. Thats part of the tweak. Those keys just don’t happen to exist on your system, so no worries
