### ISSUE TITLE
Laptop doesn't boot anymore

### ISSUE THREAD

**Issue by chrisch4n** [builtbybel/Flyby11#20]
I mistakenly "patched" my installed SSD harddrive with the USB Patch instead of the Installation Drive while creating the Boot Drive. After this my laptop stucks on boot, showing f2, f9 or F12 menu, but doesn't react on hitting one of these keys. After removal of my SSD i can start my uefi BIOS. 
So the Patch seems to have "killed" my SSD.
How can i "repair" the SSD, so that it reacts anymore or that i can reinstall Windows on it?

**Comment by Belim** [comment]
this is more than strange and technically impossible. To roll back the patch, just delete the entire $OEM$ folder in the sources directory ..if its even created?

**Comment by chrisch4n** [comment]
It's alive again.
I repaired my system Partition and uefi boot (had to install the SSD into a USB case) and it works again.
