### ISSUE TITLE
Important question

### ISSUE THREAD

**Issue by berkar-hub** [builtbybel/Flyby11#24]
i try always the method 1 on my windows 10, but get always the attached picture with the error message..

?????

[
![IMG_1952](https://github.com/user-attachments/assets/4d2233a4-4f23-4292-b03a-7819af685aa3)
](url)

**Comment by Anon-1439** [comment]
you're probably on a VPN, ironically if you aren't and you get that error you just have to use one and it might work

ProtonVPN or Windscribe should do the job for free

**Comment by Belim** [comment]
Check latest ver https://github.com/builtbybel/Flyby11/releases/tag/0.17.160
