### ISSUE TITLE
Gateway not valid

### ISSUE THREAD

**Issue by acalore88** [builtbybel/Flyby11#31]
First of all thank you for the great tool.
However, when I try method 1 I get the "Gateway not valid" error. If I open the link, I get a 404 error. I guess the link no longer points at the iso file.

**Comment by Mechmonk** [comment]
I'm also facing the same issue.

**Comment by Faelwolf** [comment]
Same as well

**Comment by Belim** [comment]
Please replace the Fido.ps1 script in the "upgraider" folder with the version you can download here: https://github.com/pbatard/Fido/blob/master/Fido.ps1"

**Comment by acalore88** [comment]
Thank you.
