### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mieik** [builtbybel/Flyby11#4]
21:48:27 - Mount-DiskImage : Impossibile trovare un parametro posizionale che accetta l'argomento 
21:48:27 - 'Downloads\Win11_24H2_Italian_x64.iso'.
21:48:27 - In riga:1 car:1
21:48:27 - + Mount-DiskImage -ImagePath D:\Download\Chrome Downloads\Win11_24H2_It ...
21:48:27 - + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
21:48:27 -     + CategoryInfo          : InvalidArgument: (:) [Mount-DiskImage], ParameterBindingException
21:48:27 -     + FullyQualifiedErrorId : PositionalParameterNotFound,Mount-DiskImage
21:48:28 -  
21:48:28 - Mount-DiskImage : Impossibile trovare un parametro posizionale che accetta l'argomento 
'Downloads\Win11_24H2_Italian_x64.iso'.
In riga:1 car:1
+ Mount-DiskImage -ImagePath D:\Download\Chrome Downloads\Win11_24H2_It ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Mount-DiskImage], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Mount-DiskImage
 

21:48:28 - Failed to get mounted drive letter.

**Comment by igorruckert** [comment]
Same here:

19:29:45 - Mounting ISO: W:\WINDOWS\WINDOWS 11\Win11_24H2_BrazilianPortuguese_x64.iso...
19:29:51 - Mount-DiskImage : NÆo ‚ poss¡vel localizar um parƒmetro posicional que aceite o argumento 
19:29:51 - '11\Win11_24H2_BrazilianPortuguese_x64.iso'.
19:29:51 - No linha:1 caractere:1
19:29:51 - + Mount-DiskImage -ImagePath W:\WINDOWS\WINDOWS 11\Win11_24H2_Brazilian ...
19:29:51 - + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19:29:51 -     + CategoryInfo          : InvalidArgument: (:) [Mount-DiskImage], ParameterBindingException
19:29:51 -     + FullyQualifiedErrorId : PositionalParameterNotFound,Mount-DiskImage
19:29:51 -  
19:29:51 - Mount-DiskImage : NÆo ‚ poss¡vel localizar um parƒmetro posicional que aceite o argumento 
'11\Win11_24H2_BrazilianPortuguese_x64.iso'.
No linha:1 caractere:1
+ Mount-DiskImage -ImagePath W:\WINDOWS\WINDOWS 11\Win11_24H2_Brazilian ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Mount-DiskImage], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Mount-DiskImage
 

19:29:51 - Failed to get mounted drive letter.
19:29:51 - Failed to mount ISO. Exiting.

**Comment by Belim** [comment]
Please test the latest build. How many drives are currently mounted?

**Comment by igorruckert** [comment]
Already tested with latest build, no drive mounted.

**Comment by mieik** [comment]
Hey, I've done it manually with command prompt so cannot test it anymore, but good luck!

**Comment by micpouli** [comment]
Hi,
I have the same issue. This is the errorcode I get:
15:10:59 - Mounting ISO: C:\Downloads\Win11_24H2_Dutch_x64 (1).iso...
15:11:03 - Mount-DiskImage : A positional parameter cannot be found that accepts argument '$null'.
15:11:03 - At line:1 char:1
15:11:03 - + Mount-DiskImage -ImagePath C:\Downloads\Win11_24H2_Dutch_x64 (1).iso
15:11:03 - + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
15:11:03 -     + CategoryInfo          : InvalidArgument: (:) [Mount-DiskImage], ParameterBindingException
15:11:03 -     + FullyQualifiedErrorId : PositionalParameterNotFound,Mount-DiskImage
15:11:03 -  
15:11:03 - Mount-DiskImage : A positional parameter cannot be found that accepts argument '$null'.
At line:1 char:1
+ Mount-DiskImage -ImagePath C:\Downloads\Win11_24H2_Dutch_x64 (1).iso
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Mount-DiskImage], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Mount-DiskImage
 

15:11:03 - Failed to get mounted drive letter.
15:11:03 - Failed to mount ISO. Exiting.
