### ISSUE TITLE
Downloading 24H2 is not good on older computers

### ISSUE THREAD

**Issue by solmoller** [builtbybel/Flyby11#7]
Brilliant tool, thanks very much!

I had an error message after having installed the ISO:
`"The installation failed in the SAFE_OS phase with an error during BOOT operation"`
It turns out, that the 24H2 image is slightly more demanding than the 23H2 image, I downloaded the 23H2 ISO image from here:

[https://massgrave.dev/windows_11_links](https://massgrave.dev/windows_11_links)
And hey presto, Windows 11 on a machine from 2011

BR Henrik

**Comment by Belim** [comment]
Ive seen that before myself; https://www.elevenforum.com/t/installation-failed-in-safe_os-phase-with-an-error-during-boot-operation-0xc1900101-0x20017.2528
 However, I haven't experienced it myself yet
